/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttainmentLevel = { 'level1' : null } |
  { 'level2' : null } |
  { 'level3' : null };
export interface ClassReport {
  'topPerformers' : Array<string>,
  'bottomPerformers' : Array<string>,
  'examId' : ExamId,
  'examName' : string,
  'subjectSummaries' : Array<ClassSubjectSummary>,
  'className' : string,
}
export interface ClassSubjectSummary {
  'bottomStudent' : [] | [string],
  'topStudent' : [] | [string],
  'subjectName' : string,
  'subjectId' : SubjectId,
  'averageScore' : number,
}
export interface CoAttainment {
  'co' : string,
  'attainmentLevel' : AttainmentLevel,
  'passPercentage' : number,
}
export interface CoAttainmentAnalysis {
  'subjectCode' : string,
  'totalStudents' : bigint,
  'coAttainments' : Array<CoAttainment>,
}
export interface CoMarks {
  'co1' : bigint,
  'co2' : bigint,
  'co3' : bigint,
  'co4' : bigint,
  'co5' : bigint,
}
export interface CreateExamRequest {
  'date' : string,
  'name' : string,
  'maxMarks' : bigint,
  'examType' : ExamType,
}
export interface CreateStudentRequest {
  'contact' : string,
  'name' : string,
  'enrollmentStatus' : EnrollmentStatus,
  'rollNumber' : string,
  'className' : string,
}
export interface CreateSubjectRequest { 'code' : string, 'name' : string }
export interface CreateTeacherRequest {
  'principal' : UserId,
  'name' : string,
  'role' : TeacherRole,
}
export type EnrollmentStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'graduated' : null } |
  { 'suspended' : null };
export type ExamId = bigint;
export type ExamType = { 'final' : null } |
  { 'practical' : null } |
  { 'assignment' : null } |
  { 'quiz' : null } |
  { 'midterm' : null };
export interface ExamView {
  'id' : ExamId,
  'date' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'maxMarks' : bigint,
  'examType' : ExamType,
}
export type MarkId = bigint;
export interface MarkView {
  'id' : MarkId,
  'studentId' : StudentId,
  'marksObtained' : bigint,
  'createdAt' : Timestamp,
  'subjectId' : SubjectId,
  'examId' : ExamId,
  'remarks' : string,
  'enteredBy' : UserId,
}
export interface PerformanceRecordView {
  'id' : bigint,
  'studentId' : StudentId,
  'subjectCode' : string,
  'assignment' : CoMarks,
  'quiz' : CoMarks,
  'midsem' : CoMarks,
  'totalMark' : bigint,
  'attendance' : CoMarks,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
}
export interface StudentExamPerformance {
  'subjectName' : string,
  'marksObtained' : bigint,
  'subjectId' : SubjectId,
  'maxMarks' : bigint,
  'examId' : ExamId,
  'examName' : string,
  'passed' : boolean,
}
export type StudentId = bigint;
export interface StudentReport {
  'studentId' : StudentId,
  'studentName' : string,
  'performances' : Array<StudentExamPerformance>,
  'rollNumber' : string,
  'overallPassed' : boolean,
  'className' : string,
  'averageScore' : number,
}
export interface StudentView {
  'id' : StudentId,
  'contact' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'enrollmentStatus' : EnrollmentStatus,
  'rollNumber' : string,
  'className' : string,
}
export type SubjectId = bigint;
export interface SubjectView {
  'id' : SubjectId,
  'code' : string,
  'name' : string,
  'createdAt' : Timestamp,
}
export type TeacherRole = { 'admin' : null } |
  { 'teacher' : null };
export interface TeacherView {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : TeacherRole,
}
export type Timestamp = bigint;
export interface UpdateStudentRequest {
  'contact' : string,
  'name' : string,
  'enrollmentStatus' : EnrollmentStatus,
  'rollNumber' : string,
  'className' : string,
}
export interface UpdateTeacherRequest { 'name' : string, 'role' : TeacherRole }
export interface UploadRecordRequest {
  'studentId' : StudentId,
  'subjectCode' : string,
  'assignment' : CoMarks,
  'quiz' : CoMarks,
  'midsem' : CoMarks,
  'attendance' : CoMarks,
}
export interface UpsertMarkRequest {
  'studentId' : StudentId,
  'marksObtained' : bigint,
  'subjectId' : SubjectId,
  'examId' : ExamId,
  'remarks' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExam' : ActorMethod<[CreateExamRequest], ExamView>,
  'createStudent' : ActorMethod<[CreateStudentRequest], StudentView>,
  'createSubject' : ActorMethod<[CreateSubjectRequest], SubjectView>,
  'createTeacher' : ActorMethod<[CreateTeacherRequest], TeacherView>,
  'deleteExam' : ActorMethod<[ExamId], undefined>,
  'deleteStudent' : ActorMethod<[StudentId], undefined>,
  'deleteSubject' : ActorMethod<[SubjectId], undefined>,
  'deleteTeacher' : ActorMethod<[UserId], undefined>,
  'deleteUploadedRecord' : ActorMethod<[bigint], boolean>,
  'getCallerTeacherProfile' : ActorMethod<[], [] | [TeacherView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassReport' : ActorMethod<[string, ExamId], ClassReport>,
  'getCoAttainmentAnalysis' : ActorMethod<[string], CoAttainmentAnalysis>,
  'getStudent' : ActorMethod<[StudentId], [] | [StudentView]>,
  'getStudentReport' : ActorMethod<[StudentId], [] | [StudentReport]>,
  'getTeacher' : ActorMethod<[UserId], [] | [TeacherView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listExams' : ActorMethod<[], Array<ExamView>>,
  'listMarksForStudent' : ActorMethod<[StudentId], Array<MarkView>>,
  'listStudents' : ActorMethod<[], Array<StudentView>>,
  'listSubjects' : ActorMethod<[], Array<SubjectView>>,
  'listTeachers' : ActorMethod<[], Array<TeacherView>>,
  'listUploadedPerformance' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<PerformanceRecordView>
  >,
  'registerOrUpdateTeacher' : ActorMethod<[string], TeacherView>,
  'searchStudents' : ActorMethod<[string], Array<StudentView>>,
  'updateExam' : ActorMethod<[ExamId, CreateExamRequest], ExamView>,
  'updateStudent' : ActorMethod<[StudentId, UpdateStudentRequest], StudentView>,
  'updateSubject' : ActorMethod<[SubjectId, CreateSubjectRequest], SubjectView>,
  'updateTeacher' : ActorMethod<[UserId, UpdateTeacherRequest], TeacherView>,
  'uploadPerformanceData' : ActorMethod<
    [Array<UploadRecordRequest>],
    Array<PerformanceRecordView>
  >,
  'upsertMark' : ActorMethod<[UpsertMarkRequest], MarkView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];