/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExamType = IDL.Variant({
  'final' : IDL.Null,
  'practical' : IDL.Null,
  'assignment' : IDL.Null,
  'quiz' : IDL.Null,
  'midterm' : IDL.Null,
});
export const CreateExamRequest = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'maxMarks' : IDL.Nat,
  'examType' : ExamType,
});
export const ExamId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ExamView = IDL.Record({
  'id' : ExamId,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'maxMarks' : IDL.Nat,
  'examType' : ExamType,
});
export const EnrollmentStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'graduated' : IDL.Null,
  'suspended' : IDL.Null,
});
export const CreateStudentRequest = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'enrollmentStatus' : EnrollmentStatus,
  'rollNumber' : IDL.Text,
  'className' : IDL.Text,
});
export const StudentId = IDL.Nat;
export const StudentView = IDL.Record({
  'id' : StudentId,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'enrollmentStatus' : EnrollmentStatus,
  'rollNumber' : IDL.Text,
  'className' : IDL.Text,
});
export const CreateSubjectRequest = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
});
export const SubjectId = IDL.Nat;
export const SubjectView = IDL.Record({
  'id' : SubjectId,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const UserId = IDL.Principal;
export const TeacherRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
});
export const CreateTeacherRequest = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'role' : TeacherRole,
});
export const TeacherView = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : TeacherRole,
});
export const ClassSubjectSummary = IDL.Record({
  'bottomStudent' : IDL.Opt(IDL.Text),
  'topStudent' : IDL.Opt(IDL.Text),
  'subjectName' : IDL.Text,
  'subjectId' : SubjectId,
  'averageScore' : IDL.Float64,
});
export const ClassReport = IDL.Record({
  'topPerformers' : IDL.Vec(IDL.Text),
  'bottomPerformers' : IDL.Vec(IDL.Text),
  'examId' : ExamId,
  'examName' : IDL.Text,
  'subjectSummaries' : IDL.Vec(ClassSubjectSummary),
  'className' : IDL.Text,
});
export const AttainmentLevel = IDL.Variant({
  'level1' : IDL.Null,
  'level2' : IDL.Null,
  'level3' : IDL.Null,
});
export const CoAttainment = IDL.Record({
  'co' : IDL.Text,
  'attainmentLevel' : AttainmentLevel,
  'passPercentage' : IDL.Float64,
});
export const CoAttainmentAnalysis = IDL.Record({
  'subjectCode' : IDL.Text,
  'totalStudents' : IDL.Nat,
  'coAttainments' : IDL.Vec(CoAttainment),
});
export const StudentExamPerformance = IDL.Record({
  'subjectName' : IDL.Text,
  'marksObtained' : IDL.Nat,
  'subjectId' : SubjectId,
  'maxMarks' : IDL.Nat,
  'examId' : ExamId,
  'examName' : IDL.Text,
  'passed' : IDL.Bool,
});
export const StudentReport = IDL.Record({
  'studentId' : StudentId,
  'studentName' : IDL.Text,
  'performances' : IDL.Vec(StudentExamPerformance),
  'rollNumber' : IDL.Text,
  'overallPassed' : IDL.Bool,
  'className' : IDL.Text,
  'averageScore' : IDL.Float64,
});
export const MarkId = IDL.Nat;
export const MarkView = IDL.Record({
  'id' : MarkId,
  'studentId' : StudentId,
  'marksObtained' : IDL.Nat,
  'createdAt' : Timestamp,
  'subjectId' : SubjectId,
  'examId' : ExamId,
  'remarks' : IDL.Text,
  'enteredBy' : UserId,
});
export const CoMarks = IDL.Record({
  'co1' : IDL.Nat,
  'co2' : IDL.Nat,
  'co3' : IDL.Nat,
  'co4' : IDL.Nat,
  'co5' : IDL.Nat,
});
export const PerformanceRecordView = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : StudentId,
  'subjectCode' : IDL.Text,
  'assignment' : CoMarks,
  'quiz' : CoMarks,
  'midsem' : CoMarks,
  'totalMark' : IDL.Nat,
  'attendance' : CoMarks,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
});
export const UpdateStudentRequest = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'enrollmentStatus' : EnrollmentStatus,
  'rollNumber' : IDL.Text,
  'className' : IDL.Text,
});
export const UpdateTeacherRequest = IDL.Record({
  'name' : IDL.Text,
  'role' : TeacherRole,
});
export const UploadRecordRequest = IDL.Record({
  'studentId' : StudentId,
  'subjectCode' : IDL.Text,
  'assignment' : CoMarks,
  'quiz' : CoMarks,
  'midsem' : CoMarks,
  'attendance' : CoMarks,
});
export const UpsertMarkRequest = IDL.Record({
  'studentId' : StudentId,
  'marksObtained' : IDL.Nat,
  'subjectId' : SubjectId,
  'examId' : ExamId,
  'remarks' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExam' : IDL.Func([CreateExamRequest], [ExamView], []),
  'createStudent' : IDL.Func([CreateStudentRequest], [StudentView], []),
  'createSubject' : IDL.Func([CreateSubjectRequest], [SubjectView], []),
  'createTeacher' : IDL.Func([CreateTeacherRequest], [TeacherView], []),
  'deleteExam' : IDL.Func([ExamId], [], []),
  'deleteStudent' : IDL.Func([StudentId], [], []),
  'deleteSubject' : IDL.Func([SubjectId], [], []),
  'deleteTeacher' : IDL.Func([UserId], [], []),
  'deleteUploadedRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerTeacherProfile' : IDL.Func([], [IDL.Opt(TeacherView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassReport' : IDL.Func([IDL.Text, ExamId], [ClassReport], ['query']),
  'getCoAttainmentAnalysis' : IDL.Func(
      [IDL.Text],
      [CoAttainmentAnalysis],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentView)], ['query']),
  'getStudentReport' : IDL.Func(
      [StudentId],
      [IDL.Opt(StudentReport)],
      ['query'],
    ),
  'getTeacher' : IDL.Func([UserId], [IDL.Opt(TeacherView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listExams' : IDL.Func([], [IDL.Vec(ExamView)], ['query']),
  'listMarksForStudent' : IDL.Func([StudentId], [IDL.Vec(MarkView)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(SubjectView)], ['query']),
  'listTeachers' : IDL.Func([], [IDL.Vec(TeacherView)], ['query']),
  'listUploadedPerformance' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(PerformanceRecordView)],
      ['query'],
    ),
  'registerOrUpdateTeacher' : IDL.Func([IDL.Text], [TeacherView], []),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(StudentView)], ['query']),
  'updateExam' : IDL.Func([ExamId, CreateExamRequest], [ExamView], []),
  'updateStudent' : IDL.Func(
      [StudentId, UpdateStudentRequest],
      [StudentView],
      [],
    ),
  'updateSubject' : IDL.Func(
      [SubjectId, CreateSubjectRequest],
      [SubjectView],
      [],
    ),
  'updateTeacher' : IDL.Func([UserId, UpdateTeacherRequest], [TeacherView], []),
  'uploadPerformanceData' : IDL.Func(
      [IDL.Vec(UploadRecordRequest)],
      [IDL.Vec(PerformanceRecordView)],
      [],
    ),
  'upsertMark' : IDL.Func([UpsertMarkRequest], [MarkView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExamType = IDL.Variant({
    'final' : IDL.Null,
    'practical' : IDL.Null,
    'assignment' : IDL.Null,
    'quiz' : IDL.Null,
    'midterm' : IDL.Null,
  });
  const CreateExamRequest = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'maxMarks' : IDL.Nat,
    'examType' : ExamType,
  });
  const ExamId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ExamView = IDL.Record({
    'id' : ExamId,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'maxMarks' : IDL.Nat,
    'examType' : ExamType,
  });
  const EnrollmentStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'graduated' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const CreateStudentRequest = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'enrollmentStatus' : EnrollmentStatus,
    'rollNumber' : IDL.Text,
    'className' : IDL.Text,
  });
  const StudentId = IDL.Nat;
  const StudentView = IDL.Record({
    'id' : StudentId,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'enrollmentStatus' : EnrollmentStatus,
    'rollNumber' : IDL.Text,
    'className' : IDL.Text,
  });
  const CreateSubjectRequest = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
  });
  const SubjectId = IDL.Nat;
  const SubjectView = IDL.Record({
    'id' : SubjectId,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const UserId = IDL.Principal;
  const TeacherRole = IDL.Variant({ 'admin' : IDL.Null, 'teacher' : IDL.Null });
  const CreateTeacherRequest = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'role' : TeacherRole,
  });
  const TeacherView = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : TeacherRole,
  });
  const ClassSubjectSummary = IDL.Record({
    'bottomStudent' : IDL.Opt(IDL.Text),
    'topStudent' : IDL.Opt(IDL.Text),
    'subjectName' : IDL.Text,
    'subjectId' : SubjectId,
    'averageScore' : IDL.Float64,
  });
  const ClassReport = IDL.Record({
    'topPerformers' : IDL.Vec(IDL.Text),
    'bottomPerformers' : IDL.Vec(IDL.Text),
    'examId' : ExamId,
    'examName' : IDL.Text,
    'subjectSummaries' : IDL.Vec(ClassSubjectSummary),
    'className' : IDL.Text,
  });
  const AttainmentLevel = IDL.Variant({
    'level1' : IDL.Null,
    'level2' : IDL.Null,
    'level3' : IDL.Null,
  });
  const CoAttainment = IDL.Record({
    'co' : IDL.Text,
    'attainmentLevel' : AttainmentLevel,
    'passPercentage' : IDL.Float64,
  });
  const CoAttainmentAnalysis = IDL.Record({
    'subjectCode' : IDL.Text,
    'totalStudents' : IDL.Nat,
    'coAttainments' : IDL.Vec(CoAttainment),
  });
  const StudentExamPerformance = IDL.Record({
    'subjectName' : IDL.Text,
    'marksObtained' : IDL.Nat,
    'subjectId' : SubjectId,
    'maxMarks' : IDL.Nat,
    'examId' : ExamId,
    'examName' : IDL.Text,
    'passed' : IDL.Bool,
  });
  const StudentReport = IDL.Record({
    'studentId' : StudentId,
    'studentName' : IDL.Text,
    'performances' : IDL.Vec(StudentExamPerformance),
    'rollNumber' : IDL.Text,
    'overallPassed' : IDL.Bool,
    'className' : IDL.Text,
    'averageScore' : IDL.Float64,
  });
  const MarkId = IDL.Nat;
  const MarkView = IDL.Record({
    'id' : MarkId,
    'studentId' : StudentId,
    'marksObtained' : IDL.Nat,
    'createdAt' : Timestamp,
    'subjectId' : SubjectId,
    'examId' : ExamId,
    'remarks' : IDL.Text,
    'enteredBy' : UserId,
  });
  const CoMarks = IDL.Record({
    'co1' : IDL.Nat,
    'co2' : IDL.Nat,
    'co3' : IDL.Nat,
    'co4' : IDL.Nat,
    'co5' : IDL.Nat,
  });
  const PerformanceRecordView = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : StudentId,
    'subjectCode' : IDL.Text,
    'assignment' : CoMarks,
    'quiz' : CoMarks,
    'midsem' : CoMarks,
    'totalMark' : IDL.Nat,
    'attendance' : CoMarks,
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
  });
  const UpdateStudentRequest = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'enrollmentStatus' : EnrollmentStatus,
    'rollNumber' : IDL.Text,
    'className' : IDL.Text,
  });
  const UpdateTeacherRequest = IDL.Record({
    'name' : IDL.Text,
    'role' : TeacherRole,
  });
  const UploadRecordRequest = IDL.Record({
    'studentId' : StudentId,
    'subjectCode' : IDL.Text,
    'assignment' : CoMarks,
    'quiz' : CoMarks,
    'midsem' : CoMarks,
    'attendance' : CoMarks,
  });
  const UpsertMarkRequest = IDL.Record({
    'studentId' : StudentId,
    'marksObtained' : IDL.Nat,
    'subjectId' : SubjectId,
    'examId' : ExamId,
    'remarks' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExam' : IDL.Func([CreateExamRequest], [ExamView], []),
    'createStudent' : IDL.Func([CreateStudentRequest], [StudentView], []),
    'createSubject' : IDL.Func([CreateSubjectRequest], [SubjectView], []),
    'createTeacher' : IDL.Func([CreateTeacherRequest], [TeacherView], []),
    'deleteExam' : IDL.Func([ExamId], [], []),
    'deleteStudent' : IDL.Func([StudentId], [], []),
    'deleteSubject' : IDL.Func([SubjectId], [], []),
    'deleteTeacher' : IDL.Func([UserId], [], []),
    'deleteUploadedRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerTeacherProfile' : IDL.Func([], [IDL.Opt(TeacherView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassReport' : IDL.Func([IDL.Text, ExamId], [ClassReport], ['query']),
    'getCoAttainmentAnalysis' : IDL.Func(
        [IDL.Text],
        [CoAttainmentAnalysis],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentView)], ['query']),
    'getStudentReport' : IDL.Func(
        [StudentId],
        [IDL.Opt(StudentReport)],
        ['query'],
      ),
    'getTeacher' : IDL.Func([UserId], [IDL.Opt(TeacherView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listExams' : IDL.Func([], [IDL.Vec(ExamView)], ['query']),
    'listMarksForStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(MarkView)],
        ['query'],
      ),
    'listStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(SubjectView)], ['query']),
    'listTeachers' : IDL.Func([], [IDL.Vec(TeacherView)], ['query']),
    'listUploadedPerformance' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(PerformanceRecordView)],
        ['query'],
      ),
    'registerOrUpdateTeacher' : IDL.Func([IDL.Text], [TeacherView], []),
    'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(StudentView)], ['query']),
    'updateExam' : IDL.Func([ExamId, CreateExamRequest], [ExamView], []),
    'updateStudent' : IDL.Func(
        [StudentId, UpdateStudentRequest],
        [StudentView],
        [],
      ),
    'updateSubject' : IDL.Func(
        [SubjectId, CreateSubjectRequest],
        [SubjectView],
        [],
      ),
    'updateTeacher' : IDL.Func(
        [UserId, UpdateTeacherRequest],
        [TeacherView],
        [],
      ),
    'uploadPerformanceData' : IDL.Func(
        [IDL.Vec(UploadRecordRequest)],
        [IDL.Vec(PerformanceRecordView)],
        [],
      ),
    'upsertMark' : IDL.Func([UpsertMarkRequest], [MarkView], []),
  });
};

export const init = ({ IDL }) => { return []; };