/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateTeacherRequest {
    principal: UserId;
    name: string;
    role: TeacherRole;
}
export interface TeacherView {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: TeacherRole;
}
export interface CreateStudentRequest {
    contact: string;
    name: string;
    enrollmentStatus: EnrollmentStatus;
    rollNumber: string;
    className: string;
}
export type ExamId = bigint;
export interface CreateExamRequest {
    date: string;
    name: string;
    maxMarks: bigint;
    examType: ExamType;
}
export interface CoAttainmentAnalysis {
    subjectCode: string;
    totalStudents: bigint;
    coAttainments: Array<CoAttainment>;
}
export type MarkId = bigint;
export interface UploadRecordRequest {
    studentId: StudentId;
    subjectCode: string;
    assignment: CoMarks;
    quiz: CoMarks;
    midsem: CoMarks;
    attendance: CoMarks;
}
export interface SubjectView {
    id: SubjectId;
    code: string;
    name: string;
    createdAt: Timestamp;
}
export interface StudentReport {
    studentId: StudentId;
    studentName: string;
    performances: Array<StudentExamPerformance>;
    rollNumber: string;
    overallPassed: boolean;
    className: string;
    averageScore: number;
}
export interface PerformanceRecordView {
    id: bigint;
    studentId: StudentId;
    subjectCode: string;
    assignment: CoMarks;
    quiz: CoMarks;
    midsem: CoMarks;
    totalMark: bigint;
    attendance: CoMarks;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
}
export interface ExamView {
    id: ExamId;
    date: string;
    name: string;
    createdAt: Timestamp;
    maxMarks: bigint;
    examType: ExamType;
}
export interface MarkView {
    id: MarkId;
    studentId: StudentId;
    marksObtained: bigint;
    createdAt: Timestamp;
    subjectId: SubjectId;
    examId: ExamId;
    remarks: string;
    enteredBy: UserId;
}
export interface CoMarks {
    co1: bigint;
    co2: bigint;
    co3: bigint;
    co4: bigint;
    co5: bigint;
}
export type SubjectId = bigint;
export interface StudentView {
    id: StudentId;
    contact: string;
    name: string;
    createdAt: Timestamp;
    enrollmentStatus: EnrollmentStatus;
    rollNumber: string;
    className: string;
}
export interface CreateSubjectRequest {
    code: string;
    name: string;
}
export interface ClassReport {
    topPerformers: Array<string>;
    bottomPerformers: Array<string>;
    examId: ExamId;
    examName: string;
    subjectSummaries: Array<ClassSubjectSummary>;
    className: string;
}
export interface ClassSubjectSummary {
    bottomStudent?: string;
    topStudent?: string;
    subjectName: string;
    subjectId: SubjectId;
    averageScore: number;
}
export type StudentId = bigint;
export type UserId = Principal;
export interface StudentExamPerformance {
    subjectName: string;
    marksObtained: bigint;
    subjectId: SubjectId;
    maxMarks: bigint;
    examId: ExamId;
    examName: string;
    passed: boolean;
}
export interface UpsertMarkRequest {
    studentId: StudentId;
    marksObtained: bigint;
    subjectId: SubjectId;
    examId: ExamId;
    remarks: string;
}
export interface UpdateStudentRequest {
    contact: string;
    name: string;
    enrollmentStatus: EnrollmentStatus;
    rollNumber: string;
    className: string;
}
export interface UpdateTeacherRequest {
    name: string;
    role: TeacherRole;
}
export interface CoAttainment {
    co: string;
    attainmentLevel: AttainmentLevel;
    passPercentage: number;
}
export enum AttainmentLevel {
    level1 = "level1",
    level2 = "level2",
    level3 = "level3"
}
export enum EnrollmentStatus {
    active = "active",
    inactive = "inactive",
    graduated = "graduated",
    suspended = "suspended"
}
export enum ExamType {
    final_ = "final",
    practical = "practical",
    assignment = "assignment",
    quiz = "quiz",
    midterm = "midterm"
}
export enum TeacherRole {
    admin = "admin",
    teacher = "teacher"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createExam(req: CreateExamRequest): Promise<ExamView>;
    createStudent(req: CreateStudentRequest): Promise<StudentView>;
    createSubject(req: CreateSubjectRequest): Promise<SubjectView>;
    createTeacher(req: CreateTeacherRequest): Promise<TeacherView>;
    deleteExam(id: ExamId): Promise<void>;
    deleteStudent(id: StudentId): Promise<void>;
    deleteSubject(id: SubjectId): Promise<void>;
    deleteTeacher(id: UserId): Promise<void>;
    deleteUploadedRecord(id: bigint): Promise<boolean>;
    getCallerTeacherProfile(): Promise<TeacherView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClassReport(className: string, examId: ExamId): Promise<ClassReport>;
    getCoAttainmentAnalysis(subjectCode: string): Promise<CoAttainmentAnalysis>;
    getStudent(id: StudentId): Promise<StudentView | null>;
    getStudentReport(studentId: StudentId): Promise<StudentReport | null>;
    getTeacher(id: UserId): Promise<TeacherView | null>;
    isCallerAdmin(): Promise<boolean>;
    listExams(): Promise<Array<ExamView>>;
    listMarksForStudent(studentId: StudentId): Promise<Array<MarkView>>;
    listStudents(): Promise<Array<StudentView>>;
    listSubjects(): Promise<Array<SubjectView>>;
    listTeachers(): Promise<Array<TeacherView>>;
    listUploadedPerformance(subjectCode: string | null, studentId: bigint | null): Promise<Array<PerformanceRecordView>>;
    registerOrUpdateTeacher(name: string): Promise<TeacherView>;
    searchStudents(term: string): Promise<Array<StudentView>>;
    updateExam(id: ExamId, req: CreateExamRequest): Promise<ExamView>;
    updateStudent(id: StudentId, req: UpdateStudentRequest): Promise<StudentView>;
    updateSubject(id: SubjectId, req: CreateSubjectRequest): Promise<SubjectView>;
    updateTeacher(id: UserId, req: UpdateTeacherRequest): Promise<TeacherView>;
    uploadPerformanceData(requests: Array<UploadRecordRequest>): Promise<Array<PerformanceRecordView>>;
    upsertMark(req: UpsertMarkRequest): Promise<MarkView>;
}
import type { AttainmentLevel as _AttainmentLevel, ClassReport as _ClassReport, ClassSubjectSummary as _ClassSubjectSummary, CoAttainment as _CoAttainment, CoAttainmentAnalysis as _CoAttainmentAnalysis, CreateExamRequest as _CreateExamRequest, CreateStudentRequest as _CreateStudentRequest, CreateTeacherRequest as _CreateTeacherRequest, EnrollmentStatus as _EnrollmentStatus, ExamId as _ExamId, ExamType as _ExamType, ExamView as _ExamView, StudentId as _StudentId, StudentReport as _StudentReport, StudentView as _StudentView, SubjectId as _SubjectId, TeacherRole as _TeacherRole, TeacherView as _TeacherView, Timestamp as _Timestamp, UpdateStudentRequest as _UpdateStudentRequest, UpdateTeacherRequest as _UpdateTeacherRequest, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createExam(arg0: CreateExamRequest): Promise<ExamView> {
        if (this.processError) {
            try {
                const result = await this.actor.createExam(to_candid_CreateExamRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExamView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExam(to_candid_CreateExamRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExamView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: CreateStudentRequest): Promise<StudentView> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(to_candid_CreateStudentRequest_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_StudentView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(to_candid_CreateStudentRequest_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_StudentView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSubject(arg0: CreateSubjectRequest): Promise<SubjectView> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(arg0);
            return result;
        }
    }
    async createTeacher(arg0: CreateTeacherRequest): Promise<TeacherView> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacher(to_candid_CreateTeacherRequest_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TeacherView_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacher(to_candid_CreateTeacherRequest_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TeacherView_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteExam(arg0: ExamId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExam(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: SubjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async deleteUploadedRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUploadedRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUploadedRecord(arg0);
            return result;
        }
    }
    async getCallerTeacherProfile(): Promise<TeacherView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTeacherProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTeacherProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassReport(arg0: string, arg1: ExamId): Promise<ClassReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassReport(arg0, arg1);
                return from_candid_ClassReport_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassReport(arg0, arg1);
            return from_candid_ClassReport_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoAttainmentAnalysis(arg0: string): Promise<CoAttainmentAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoAttainmentAnalysis(arg0);
                return from_candid_CoAttainmentAnalysis_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoAttainmentAnalysis(arg0);
            return from_candid_CoAttainmentAnalysis_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentReport(arg0: StudentId): Promise<StudentReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentReport(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentReport(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: UserId): Promise<TeacherView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listExams(): Promise<Array<ExamView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExams();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExams();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMarksForStudent(arg0: StudentId): Promise<Array<MarkView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMarksForStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMarksForStudent(arg0);
            return result;
        }
    }
    async listStudents(): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubjects(): Promise<Array<SubjectView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubjects();
            return result;
        }
    }
    async listTeachers(): Promise<Array<TeacherView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUploadedPerformance(arg0: string | null, arg1: bigint | null): Promise<Array<PerformanceRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUploadedPerformance(to_candid_opt_n48(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUploadedPerformance(to_candid_opt_n48(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async registerOrUpdateTeacher(arg0: string): Promise<TeacherView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrUpdateTeacher(arg0);
                return from_candid_TeacherView_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrUpdateTeacher(arg0);
            return from_candid_TeacherView_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchStudents(arg0: string): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateExam(arg0: ExamId, arg1: CreateExamRequest): Promise<ExamView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExam(arg0, to_candid_CreateExamRequest_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ExamView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExam(arg0, to_candid_CreateExamRequest_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ExamView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: StudentId, arg1: UpdateStudentRequest): Promise<StudentView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_UpdateStudentRequest_n50(this._uploadFile, this._downloadFile, arg1));
                return from_candid_StudentView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_UpdateStudentRequest_n50(this._uploadFile, this._downloadFile, arg1));
            return from_candid_StudentView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubject(arg0: SubjectId, arg1: CreateSubjectRequest): Promise<SubjectView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0, arg1);
            return result;
        }
    }
    async updateTeacher(arg0: UserId, arg1: UpdateTeacherRequest): Promise<TeacherView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, to_candid_UpdateTeacherRequest_n51(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TeacherView_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, to_candid_UpdateTeacherRequest_n51(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TeacherView_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadPerformanceData(arg0: Array<UploadRecordRequest>): Promise<Array<PerformanceRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPerformanceData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPerformanceData(arg0);
            return result;
        }
    }
    async upsertMark(arg0: UpsertMarkRequest): Promise<MarkView> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMark(arg0);
            return result;
        }
    }
}
function from_candid_AttainmentLevel_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttainmentLevel): AttainmentLevel {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ClassReport_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassReport): ClassReport {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ClassSubjectSummary_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassSubjectSummary): ClassSubjectSummary {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_CoAttainmentAnalysis_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoAttainmentAnalysis): CoAttainmentAnalysis {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_CoAttainment_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoAttainment): CoAttainment {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_EnrollmentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnrollmentStatus): EnrollmentStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ExamType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamType): ExamType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ExamView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamView): ExamView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_StudentView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentView): StudentView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TeacherRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeacherRole): TeacherRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TeacherView_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeacherView): TeacherView {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeacherView]): TeacherView | null {
    return value.length === 0 ? null : from_candid_TeacherView_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentView]): StudentView | null {
    return value.length === 0 ? null : from_candid_StudentView_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentReport]): StudentReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    contact: string;
    name: string;
    createdAt: _Timestamp;
    enrollmentStatus: _EnrollmentStatus;
    rollNumber: string;
    className: string;
}): {
    id: StudentId;
    contact: string;
    name: string;
    createdAt: Timestamp;
    enrollmentStatus: EnrollmentStatus;
    rollNumber: string;
    className: string;
} {
    return {
        id: value.id,
        contact: value.contact,
        name: value.name,
        createdAt: value.createdAt,
        enrollmentStatus: from_candid_EnrollmentStatus_n17(_uploadFile, _downloadFile, value.enrollmentStatus),
        rollNumber: value.rollNumber,
        className: value.className
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _TeacherRole;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: TeacherRole;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_TeacherRole_n25(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topPerformers: Array<string>;
    bottomPerformers: Array<string>;
    examId: _ExamId;
    examName: string;
    subjectSummaries: Array<_ClassSubjectSummary>;
    className: string;
}): {
    topPerformers: Array<string>;
    bottomPerformers: Array<string>;
    examId: ExamId;
    examName: string;
    subjectSummaries: Array<ClassSubjectSummary>;
    className: string;
} {
    return {
        topPerformers: value.topPerformers,
        bottomPerformers: value.bottomPerformers,
        examId: value.examId,
        examName: value.examName,
        subjectSummaries: from_candid_vec_n32(_uploadFile, _downloadFile, value.subjectSummaries),
        className: value.className
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bottomStudent: [] | [string];
    topStudent: [] | [string];
    subjectName: string;
    subjectId: _SubjectId;
    averageScore: number;
}): {
    bottomStudent?: string;
    topStudent?: string;
    subjectName: string;
    subjectId: SubjectId;
    averageScore: number;
} {
    return {
        bottomStudent: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.bottomStudent)),
        topStudent: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.topStudent)),
        subjectName: value.subjectName,
        subjectId: value.subjectId,
        averageScore: value.averageScore
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjectCode: string;
    totalStudents: bigint;
    coAttainments: Array<_CoAttainment>;
}): {
    subjectCode: string;
    totalStudents: bigint;
    coAttainments: Array<CoAttainment>;
} {
    return {
        subjectCode: value.subjectCode,
        totalStudents: value.totalStudents,
        coAttainments: from_candid_vec_n38(_uploadFile, _downloadFile, value.coAttainments)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    co: string;
    attainmentLevel: _AttainmentLevel;
    passPercentage: number;
}): {
    co: string;
    attainmentLevel: AttainmentLevel;
    passPercentage: number;
} {
    return {
        co: value.co,
        attainmentLevel: from_candid_AttainmentLevel_n41(_uploadFile, _downloadFile, value.attainmentLevel),
        passPercentage: value.passPercentage
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExamId;
    date: string;
    name: string;
    createdAt: _Timestamp;
    maxMarks: bigint;
    examType: _ExamType;
}): {
    id: ExamId;
    date: string;
    name: string;
    createdAt: Timestamp;
    maxMarks: bigint;
    examType: ExamType;
} {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        maxMarks: value.maxMarks,
        examType: from_candid_ExamType_n9(_uploadFile, _downloadFile, value.examType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    final: null;
} | {
    practical: null;
} | {
    assignment: null;
} | {
    quiz: null;
} | {
    midterm: null;
}): ExamType {
    return "final" in value ? ExamType.final : "practical" in value ? ExamType.practical : "assignment" in value ? ExamType.assignment : "quiz" in value ? ExamType.quiz : "midterm" in value ? ExamType.midterm : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    graduated: null;
} | {
    suspended: null;
}): EnrollmentStatus {
    return "active" in value ? EnrollmentStatus.active : "inactive" in value ? EnrollmentStatus.inactive : "graduated" in value ? EnrollmentStatus.graduated : "suspended" in value ? EnrollmentStatus.suspended : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    teacher: null;
}): TeacherRole {
    return "admin" in value ? TeacherRole.admin : "teacher" in value ? TeacherRole.teacher : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level1: null;
} | {
    level2: null;
} | {
    level3: null;
}): AttainmentLevel {
    return "level1" in value ? AttainmentLevel.level1 : "level2" in value ? AttainmentLevel.level2 : "level3" in value ? AttainmentLevel.level3 : value;
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassSubjectSummary>): Array<ClassSubjectSummary> {
    return value.map((x)=>from_candid_ClassSubjectSummary_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoAttainment>): Array<CoAttainment> {
    return value.map((x)=>from_candid_CoAttainment_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExamView>): Array<ExamView> {
    return value.map((x)=>from_candid_ExamView_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentView>): Array<StudentView> {
    return value.map((x)=>from_candid_StudentView_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeacherView>): Array<TeacherView> {
    return value.map((x)=>from_candid_TeacherView_n23(_uploadFile, _downloadFile, x));
}
function to_candid_CreateExamRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateExamRequest): _CreateExamRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateStudentRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateStudentRequest): _CreateStudentRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTeacherRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTeacherRequest): _CreateTeacherRequest {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_EnrollmentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnrollmentStatus): _EnrollmentStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ExamType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamType): _ExamType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TeacherRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeacherRole): _TeacherRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStudentRequest_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStudentRequest): _UpdateStudentRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTeacherRequest_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTeacherRequest): _UpdateTeacherRequest {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    name: string;
    enrollmentStatus: EnrollmentStatus;
    rollNumber: string;
    className: string;
}): {
    contact: string;
    name: string;
    enrollmentStatus: _EnrollmentStatus;
    rollNumber: string;
    className: string;
} {
    return {
        contact: value.contact,
        name: value.name,
        enrollmentStatus: to_candid_EnrollmentStatus_n13(_uploadFile, _downloadFile, value.enrollmentStatus),
        rollNumber: value.rollNumber,
        className: value.className
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: UserId;
    name: string;
    role: TeacherRole;
}): {
    principal: _UserId;
    name: string;
    role: _TeacherRole;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: to_candid_TeacherRole_n21(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    name: string;
    maxMarks: bigint;
    examType: ExamType;
}): {
    date: string;
    name: string;
    maxMarks: bigint;
    examType: _ExamType;
} {
    return {
        date: value.date,
        name: value.name,
        maxMarks: value.maxMarks,
        examType: to_candid_ExamType_n5(_uploadFile, _downloadFile, value.examType)
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: TeacherRole;
}): {
    name: string;
    role: _TeacherRole;
} {
    return {
        name: value.name,
        role: to_candid_TeacherRole_n21(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnrollmentStatus): {
    active: null;
} | {
    inactive: null;
} | {
    graduated: null;
} | {
    suspended: null;
} {
    return value == EnrollmentStatus.active ? {
        active: null
    } : value == EnrollmentStatus.inactive ? {
        inactive: null
    } : value == EnrollmentStatus.graduated ? {
        graduated: null
    } : value == EnrollmentStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeacherRole): {
    admin: null;
} | {
    teacher: null;
} {
    return value == TeacherRole.admin ? {
        admin: null
    } : value == TeacherRole.teacher ? {
        teacher: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamType): {
    final: null;
} | {
    practical: null;
} | {
    assignment: null;
} | {
    quiz: null;
} | {
    midterm: null;
} {
    return value == ExamType.final ? {
        final_: null
    } : value == ExamType.practical ? {
        practical: null
    } : value == ExamType.assignment ? {
        assignment: null
    } : value == ExamType.quiz ? {
        quiz: null
    } : value == ExamType.midterm ? {
        midterm: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
